[build]
  command = "npm run build"
  publish = "dist/BRADYBALL-facade"

[[redirects]]
  from = "https://bradyball.net/*"
  to = "https://BRADYBALL.net/:splat"
  status = 301
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200